#!/bin/bash
str="'$*'"
# Open the Talking AI
php ./Speaking_AI.php "$str" 1 1 1 "en-US-Neural2-H";
#
#  TIP: Update 'php ./' to the full path of the PHP file then you can run:  
# $ sudo cp ./ai /usr/local/bin/ai;
# 
#  Customize the AI's pitch, speaking rate, volume, voice, language:
#   ai --voices [to see all voices available]
#   ai [chat] "$str" [pitch] 1 [speakingRate] 1 [volume] 1 [voice] 'en-US-Studio-M' [language] 'en-us'
#      [chat] Leave it as "$str" to pass the command through.
#      [pitch] 0.9 / 1 / 1.3 / 2
#      [speakingRate] 0.8 / 1 / 1.2 / 2.3
#      [volume] 0.2 / 0.4 / 0.6 / 1
#      [voice] en-US-Studio-M
#      [language] en-us
